version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
    ports:
      - "5672:5672" # RabbitMQ server
      - "15672:15672" # Management console
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
